### ISSUE TITLE
PyPi docs out of date

### ISSUE THREAD

**Issue by filip-michalsky** [browserbase/sdk-python#77]
https://pypi.org/project/browserbase/

looking at the start of the README:

`import os
from playwright.sync_api import Playwright, sync_playwright
from browserbase import Browserbase

BROWSERBASE_API_KEY = os.environ.get("BROWSERBASE_API_KEY")
BROWSERBASE_PROJECT_ID = os.environ.get("BROWSERBASE_PROJECT_ID")

bb = Browserbase(
    # This is the default and can be omitted
    api_key=BROWSERBASE_API_KEY,
)

session = client.sessions.create(
    project_id=BROWSERBASE_PROJECT_ID,
)
print(session.id)`

does not work since i think the newer version of the python SDK for `browserbase` does not pass the env vars explicitly. Also, the part of readm above is defining `bb` as the client but then using variable `client` to create a session which I think is a typo?

**Comment by kamath** [comment]
Hey @filip-michalsky thanks for bringing this to our attention! We're resolving this in the linked PR, #80.
